### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by lexciobotariu** [v0rl0x/bitcoin-bruteforce#1]
This is a nice concept, but it uses an external API, which is limited on how many requests can you send to verify the wallets.

Instead you could implement a system to check them against a DATABASE using this website http://addresses.loyce.club/ 
Download the latest Bitcoin Data and check it against that, the speed will be a lot faster. 

Here is an example of [another script](https://github.com/DavidMGilbert/btc-hack-offline/tree/main) written in python. It uses multi threading and I get 1.5m verifications a minute. 

I can't even imagine how fast will run such script written in go. 

Let me know if you have any thoughts on modifying this script to offline.

Cheers

**Comment by v0rl0x** [comment]
This has been made per your request. Enjoy!

**Comment by lexciobotariu** [comment]
Works amazing ~1.5m/min.
