### ISSUE TITLE
"Failed to check balance for 'any address that its checking': invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by hw9da** [v0rl0x/bitcoin-bruteforce#2]
Program works well at the start, but after around 1-2 minutes it gives me this error - 

"2024/02/14 20:02:46 Worker 36: Failed to check balance for 18LRpf9BWypZJLFTNL7nsxToP1EsWREpiK: invalid character '<' looking for beginning of value"

Also there is another error that comes with it.

"2024/02/14 20:10:59 Worker 3987: Failed to check balance for 1Ac3ezAJh91z5X2CixGWEj2NterKBd7pBd: Get "https://api.blockcypher.com/v1/btc/main/addrs/1Ac3ezAJh91z5X2CixGWEj2NterKBd7pBd/balance": read tcp 192.168.0.116:65287->104.20.20.251:443: wsarecv: An existing connection was forcibly closed by the remote host."

Any ideas?

Images of the problem - 

![a23123](https://github.com/v0rl0x/bitcoin-bruteforce/assets/118198952/38de7f7e-2331-4b3c-84c3-fad80ec0280f)
![asdasd](https://github.com/v0rl0x/bitcoin-bruteforce/assets/118198952/bb70fe32-5bb1-41a1-a557-896398cbf6b4)
![asdasda](https://github.com/v0rl0x/bitcoin-bruteforce/assets/118198952/5b50a951-909d-4b25-b301-2cca9e6fe42d)

**Comment by hw9da** [comment]
most likely the api just timed me out, but any ideas to fix this? for example including a place to select a list of proxies that it could use without it timing out?

**Comment by v0rl0x** [comment]
> most likely the api just timed me out, but any ideas to fix this? for example including a place to select a list of proxies that it could use without it timing out?

I will implement a way to use proxies if needed, however u should rarely hit the api limits as its limited to how many concurrent api calls it can make

**Comment by jomagalo** [comment]
Wouldn't it be more stable implementing a local bitcoin node?

**Comment by v0rl0x** [comment]
> Wouldn't it be more stable implementing a local bitcoin node?

There is an offline version with a link to the databases with all BTC wallets with funds (500 something gigabytes)
