### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Pixsy1929** [v0rl0x/bitcoin-bruteforce#3]
could You please make " how to use" section more noob friendly ? 
I don't have any idea about go

**Comment by v0rl0x** [comment]
> could You please make " how to use" section more noob friendly ? I don't have any idea about go

put the go file in the same directory, make sure golang 1.21 or higher is installed and then run:

go mod init file.go

go mod tidy

and then run go build -ldflags '-extldflags "-static"' -o bitcoin-wallet-bruteforce
