### ISSUE TITLE
balance api not working

### ISSUE THREAD

**Issue by jomagalo** [v0rl0x/bitcoin-bruteforce#4]
The function established to obtain the balance constantly crashes. 
`./bitcoin-wallet-bruteforce 1000 wallets.txt`

Could the code be modified with a more stable system, such as a local full Bitcoin node?

**Comment by v0rl0x** [comment]
API limitations, purchase an api key if needed and then modify the url in the code to match the api url.

Adding proxies here shortly, check back within a week for a proxy version of this to avoid rate limits.
