### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Raccinator** [v0rl0x/bitcoin-bruteforce#6]
2024/06/19 23:05:46 Worker 0: Failed to check balance for 1LzVniKN5C4513XpsS1JtK4dkSQC4tLmcW: invalid character '<' looking for beginning of value
2024/06/19 23:05:46 Worker 1: Failed to check balance for 1Kh31kLBxNVqFQvE12qJeD2qq4kvGymEUW: invalid character '<' looking for beginning of value
2024/06/19 23:05:49 Worker 2: Failed to check balance for 16Dad5wW9D1ahnG5BnfqQaj1ovvgNAeiLY: invalid character '<' looking for beginning of value
2024/06/19 23:05:49 Worker 1: Failed to check balance for 18WSMpWrVCJKPzhYy1mwkXCe89bcdbxA6Y: invalid character '<' looking for beginning of value
2024/06/19 23:05:49 Worker 0: Failed to check balance for 14BDo3DVZ5wxtwoXRuZaDDCz9QuyKXTUyQ: invalid character '<' looking for beginning of value
2024/06/19 23:05:52 Worker 2: Failed to check balance for 1JKyYK4e6peDbgnNA5aT1Qqy3tFYip2a2r: invalid character '<' looking for beginning of value
2024/06/19 23:05:53 Worker 1: Failed to check balance for 15XqduHqAdnHzBq43ZUbP527iWgKxfYS11: invalid character '<' looking for beginning of value
2024/06/19 23:05:53 Worker 0: Failed to check balance for 1LJzWpz1NHpnxBTmtFoPwC8Er1nGASHcYA: invalid character '<' looking for beginning of value

**Comment by v0rl0x** [comment]
API limitations, purchase an api key if needed and then modify the url in the code to match the api url. 

Adding proxies here shortly, check back within a week for a proxy version of this to avoid rate limits.
